apiVersion : apps/v1
kind : Deployment
metadata :
    name: cv-deployment
    namespace: cv-namespace
    labels :
        app : cv
spec:
    replicas : 1
    selector :
        matchLabels:
            app: cv
    template:
        metadata:
            labels:
                app: cv
        spec:
            containers:
            -   name: cv
                image: cv/cv-cv:v1
                ports:
                - containerPort : 80
                env:
                - name : EMAIL
                  valueFrom:
                    secretKeyRef:
                        name: cv-secret
                        key: email
                - name : PASSWORD
                  valueFrom:
                    secretKeyRef:
                        name: cv-secret
                        key: password
---
apiVersion: v1
kind : Service
metadata:
    name: cv-service
    namespace: cv-namespace
spec:
    #loadBalancerIP: YOU-AZURE-PUBLIC-IP-ADDRESS
    # type: LoadBalancer
    selector:
        app: cv
    ports:
        - protocol: TCP 
          port : 80
          targetPort : 80
        #   nodePort : 30000 #IN CASE YOU WANNA RUN YOUR SERVICE AS LOAD BALANCER 