apiVersion: networking.k8s.io/v1beta1
kind : Ingress
metadata:
  name: cv-ingress
  namespace: cv-namespace 
spec:
  #defaultBackend:
  #  resource:
  #    apiGroup: k8s.example.com
  #    kind: StorageBucket
  #    name: static-assets
  backend:
    serviceName: cv-service
    servicePort: 80 
  rules:
  - host: your-domain-name
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: cv-service
          servicePort: 80 
       